BE-280 - Fix missing parameter when using laravel/passport v10
netsells/passport-client-cookie pull request #8
Opened 2022-08-02 14:08 UTC by ash-phoenix-wombat

## Overview
- [ ] I have performed a self review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added sufficient logging

- [ ] New and existing tests pass locally with my changes
- [ ] The code modified as part of this PR has been covered with tests

### Problem statement

### Solution

### Dependencies

### Test procedures

### Links

JIRA: https://netsells.atlassian.net/browse/

## Deployment

### Migrations
Yes/No

### Environment variables

### Deployment notes

2022-08-03 17:43 UTC, JBonwick approved these changes

2022-08-04 07:46 UTC, kubatek94 requested changes
Thanks for the changes @ash-phoenix-wombat. I had a look through this codebase, and think that to make it work with Passport 10, it also needs to handle the decoding of the tokens in https://github.com/netsells/passport-client-cookie/blob/18a87298e15c7660ff2c1e51723ebba0dacfc733/src/Middleware/CheckClientCredentials.php#L137, as that's also going to be broken I believe.

To keep it backwards compatible and simply make a bugfix release, please update the above method so that it checks if https://github.com/firebase/php-jwt/blob/v6.0.0/src/Key.php class exists - if it does, it should call JWT::decode with an instance of that Key class, otherwise it should fallback to the current way of calling it.

References for the oldest and newest versions supported of the JWT::decode method: https://github.com/firebase/php-jwt/blob/fa8a06e96526eb7c0eeaa47e4f39be59d21f16e1/src/JWT.php#L60 and https://github.com/firebase/php-jwt/blob/018dfc4e1da92ad8a1b90adc4893f476a3b41cb8/src/JWT.php#L90

2022-08-04 07:46 UTC, kubatek94 commented on src/Middleware/ApiTokenCookieFactory.php
> +            'HS256' //Default algorithm before laravel/passport v10
```suggestion
            'HS256'
```

2022-08-04 08:36 UTC, kubatek94 approved these changes

2023-01-13 10:37 UTC, merged